catalogue/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from catalogue.views import ContactView

urlpatterns = patterns('',
    url(r'^thanks/', TemplateView.as_view(template_name="thanks.html"), name="thanks"),

    url(r'^$', ContactView.as_view(), name="homepage"),
)

katyfuks/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings

from katyfuks.views import ExtraContextTemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += i18n_patterns('',
    url(r'^become_consultant/',
        ExtraContextTemplateView.as_view(
            template_name="become_consultant.html",
            extra_context={'active_menu': "become_consultant"}
        ),
        name="become_consultant"
    ),

    url(r'^contact/',
        ExtraContextTemplateView.as_view(
            template_name="contact.html",
            extra_context={'active_menu': "contact"}
        ),
        name="contact"
    ),

    url(r'^opinions/', include('opinions.urls')),

    url(r'^', include('catalogue.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

catalogue/models.py
import os, datetime

from django.db import models
from django.utils.safestring import mark_safe


class Catalogue(models.Model):
    number = models.IntegerField()
    date_from = models.DateField(default=datetime.date.today)
    date_to = models.DateField(default=datetime.date.today)
    publication_from = models.DateField(default=datetime.date.today)
    publication_to = models.DateField(default=datetime.date.today)

    def __unicode__(self):
        return "Catalogue: " + str(self.number)

    class Meta:
        ordering = ['-number']


def get_page_upload_path(instance, filename):
    return os.path.join("uploads", "catalogue", str(instance.catalogue.number), filename)

class Page(models.Model):
    catalogue = models.ForeignKey(Catalogue)
    image = models.ImageField(upload_to=get_page_upload_path)
    position = models.IntegerField(null=True, blank=True)

    def __unicode__(self):
        return "Page: " + str(self.position)

    def save(self, *args, **kwargs):
        model = self.__class__

        if self.position is None:
            try:
                last = model.objects.filter(catalogue=self.catalogue).order_by('-position')[0]
                self.position = last.position + 1
            except IndexError:
                self.position = 1

        return super(Page, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        storage, path = self.image.storage, self.image.path

        super(Page, self).delete(*args, **kwargs)
        storage.delete(path)

    class Meta:
        ordering = ['position']

catalogue/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.core.mail import EmailMessage, send_mail
from email.mime.text import MIMEText

from katyfuks.settings import DEFAULT_FROM_EMAIL, CONTACT_EMAIL
from .models import Page


class ContactForm(forms.Form):
    name = forms.CharField()
    surename = forms.CharField()
    phone = forms.CharField()
    mail = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        body = "Kolejna osoba składa zamówienie:\n"
        body += "Imie: %s\n"
        body += "Nazwisko: %s\n"
        body += "Telefon: %s\n"
        body += "E-Mail: %s\n\n"
        body += "Message:\n"
        body += "%s\n\n"
        body += "Pozdrawiamy,\n"
        body += "Strona katyfuks"
        body = body % ( self.cleaned_data['name'], self.cleaned_data['surename'], self.cleaned_data['phone'], self.cleaned_data['mail'], self.cleaned_data['message'] )

        subject = 'Zamówienie z oriflame'

        send_mail(subject, body, DEFAULT_FROM_EMAIL, [CONTACT_EMAIL])


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        #fields = ('catalogue', 'position')

catalogue/views.py
import datetime

from django.views.generic import FormView

from catalogue.forms import ContactForm
from .models import Catalogue


class ContactView(FormView):
    template_name = "index.html"
    form_class = ContactForm
    success_url = "/thanks/"

    def form_valid(self, form):
        form.send_email()

        return super(ContactView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        try:
            catalogue = Catalogue.objects.filter(publication_from__lte=datetime.date.today).filter(publication_to__gte=datetime.date.today)[0]
        except:
            catalogue = []
        context = {
            'active_menu': "home",
            'catalogue_item': catalogue,
        }
        context.update(kwargs)

        return super(ContactView, self).get_context_data(**context)

catalogue/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block css %}
    <link rel="stylesheet" type="text/less" href="{{ STATIC_URL }}css/index.less">
    <!--zoom-->
    <link rel="stylesheet" type="text/less" href="{{ STATIC_URL }}css/cloud-zoom.css">
    <!--zoom-->
    <!--booklet-->
    <link href="{{ STATIC_URL }}css/jquery.booklet.1.4.0.css" type="text/css" rel="stylesheet" media="screen, projection, tv" />
    <!--booklet-->
{% endblock %}

{% block script %}
<script type="text/javascript">
$(document).ready(function() {
    //single book
    $('#{% trans "mybook_en" %}').booklet({
        width:  963,
        height: 446,
        easing:  null,
        easeIn:  null,
        easeOut: null,
        pagePadding: 0,
        closed: true,
        keyboard: true,
        arrows: true,
        nextControlText: "{% trans 'Next' %}",
        previousControlText: "{% trans 'Previous' %}",
        overlays: false,
        manual: false,
        pageNumbers: false,
        menu: '#custom-menu',
        pageSelector: true,
        closedFrontTitle: '',
        closedBackTitle: '',
        start: function(event, data) {
            var target_div = $('.book_page_container div:nth-child('+ (data.index + 1) +')');
            if( target_div.find('img').attr('src') == "" ) {
                var target_href = target_div.find('a');
                target_href.attr('href', target_href.attr('data-href'));
                target_div.find('img').attr('src', target_href.attr('data-href'));
                target_div.find('a').CloudZoom();
            }

            var target_div_next = target_div.next();
            if( target_div_next.find('img').attr('src') == "" ) {
                var target_href_next = target_div_next.find('a');
                target_href_next.attr('href', target_href_next.attr('data-href'));
                target_div_next.find('img').attr('src', target_href_next.attr('data-href'));
                target_div_next.find('a').CloudZoom();
            }
        }
    });

    var wraped = false;
    $(".zamknij").click(function() {
        if(!wraped) {
            $('div.form-container').wrapInner('<form action="" method="post"></form>');
            wraped = true;
        }
    });
});
</script>
{% endblock %}

{% block body_class %}front{% endblock %}

{% block form %}
<div id="form">
    <a class="{% trans 'open' %} zamknij" title="{% trans 'Open/Close' %}">{% trans 'Want to place an order?' %}</a>

    <div class="form-container">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <span>1. {% trans 'Enter your contact details' %}:</span>
            {{ form.name.errors }}
            <input id="imie" type="text" required="required" value="" placeholder="{% trans 'First name' %}" name="name"><br />
            {{ form.surename.errors }}
            <input id="nazwisko" type="text" required="required" value="" placeholder="{% trans 'Last name' %}" name="surename"><br />
            {{ form.phone.errors }}
            <input id="tel" type="text" required="required" value="" placeholder="{% trans 'Phone' %}" name="phone"><br />
            {{ form.mail.errors }}
            <input id="email" type="email" value="" placeholder="{% trans 'E-Mail' %}" name="mail"><br />
            <span>2. {% trans 'Enter product code you wish to order and quantity' %}</span>
            {{ form.message.errors }}
            <textarea required="required" placeholder="{% trans 'Message' %}" name="message"></textarea>
            <span>3. {% trans 'Click "Send"' %}:</span>
            <input type="submit" value="{% trans 'Send' %}" name="submit" />
            <span>4. {% trans 'Receive an e-mail with further information' %}</span>
            <span>5. {% trans 'Pick up beauty products at' %}:<br />"Clippers" 59 London Road <br />Bognor Regis, PO21 1DG</span>

        <div style="clear: both;"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<section id="page" class="clearfix">
    <div class="page-content">
    <h2 class="welcome">{% trans 'Why I chose Oriflame beauty products?' %}</h2>
        <article>
            {% blocktrans %}
            Oriflame offers something different - cosmetics derived from herbs and fruits. The wisdom of nature is the inspiration of cosmetics Oriflame. Carefully selected plant extracts, combined into a harmonious whole, provide products delicacy, yet highly effective. All Oriflame cosmetics are dermatologically tested in a clinical setting. Cosmetic packaging can be recycled, making them environmentally friendly. The idea of natural beauty nurtured by natural, perfectly clean Oriflame Cosmetics is today the highest quality recognition of tens of millions of men and women in the world.
            {% endblocktrans %}
            <div class="welcome1">
                {% trans 'Try Oriflame today...' %}
            </div>
        </article>
    </div>
</section>

<section id="content">
    <h2>{% trans 'Catalogue' %} <span class="num">{{ catalogue_item.number }}</span>&nbsp;&nbsp;<span class="date">({{ catalogue_item.date_from|date:"d M Y" }} - {{ catalogue_item.date_to|date:"d M Y" }})</span></h2>
    <div id="custom-menu" class="b-menu"></div>

    <div class="clear"></div>

    <div id="book">
        <div id="{% trans 'mybook_en' %}" class="book_page_container">
            {% for page in catalogue_item.page_set.all %}
            <div>
                <a href="{% if forloop.first %}{{ page.image.url }}{% endif %}" data-href="{{ page.image.url }}" class='cloud-zoom' id='zoom1'
                rel="adjustX: 0, adjustY:0,  position:'inside', showTitle:false,smoothMove:3">
                    <img src="{% if forloop.first %}{{ page.image.url }}{% endif %}" alt='' title="Optional title display" />
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

catalogue/templates/thanks.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<section id="content">
    <h2 class="head">{% trans "Message was send successfully" %}</h2>

    <div class="tekst">
        <article><span class="important">{% trans "In next few days/hours, you recive an e-mail with further information." %}</span></article>
    </div>
</section>
{% endblock %}